### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by phybros** [phybros/servertap#6]
Currently the API is completely unrestricted. Anyone who can access the ip/port where the server is running can talk to it.

There are a few different options that might be feasible:

# 1. JWT

This was the first idea I had, and started spiking it out in phybros/authentication#5 - unfortunately, without a signin mechanism, this is basically as secure as just sending a shared secret. Yes, you can generate short lived tokens on the client side using the shared HMAC secret, but that might be a bit too complicated?

# 2. Usernames/Passwords

Just create a map of `username: password` in `config.yml` and then authenticate based on that using HTTP BASIC auth.

**Comment by chesnutcase** [comment]
Considering how dangerous a malicious application can be when they have access to the API, I think security is more important than catering to users who don't understand basic networking (see: dynmap github issues)

Allow the user to generate secrets with specific scopes for each external application (e.g. this application can only view the list of online players __and nothing else__). This way, users are aware of what permissions they are granting to each application. A simplified version of OAuth if you will. Then pass them in the header or something (`X-APPLICATION-ID` and `X-API-KEY`), I think it's easier than HTTP basic auth.

For the record, if you do imagine the majority of client applications are going to be user-facing applications like the web console (and not headless data aggregators / automation scripts), then a full OAuth implementation might be worth looking into.

**Comment by Diddyy** [comment]
Not sure if these are of any use?
https://javalin.io/2018/09/11/javalin-jwt-example.html
https://javalin.io/documentation#access-manager

**Comment by MorgVerd** [comment]
For now, a simple and yet effective method I use is just to write a very simple API to sit in-between requests to servertap. Then I can just run the servertap API locally only and preform the authentication I need on the public facing mediation API.

A tad over engineered but it gets the job done.

**Comment by phybros** [comment]
Currently working on an implementation that will allow you to put something like this in your config.yml

```yaml
auth:
  # a key that has ultimate power
  - name: my-key
    key: 123abcsupersecretkey
    allow:
      - "*"
  # A key that can only access worlds and players
  - name: basic-key
    key: redrumredrum4567889
    deny:
      - "*"
    allow:
      - "world"
      - "worlds"
      - "players/*"
```

Just need to figure out if we shuold have separate permissions for read v.s. write, or just have a flag called `readOnly` on each `key` that will determine its level of access to the specified endpoints.

I welcome thoughts, ideas, critique etc
